
import os
import time
import colorama
from colorama import *
while True:
    os.system("clear")
    print(f"{Fore.LIGHTBLUE_EX}QuboScanner")
    print("")
    print(f"{Fore.LIGHTGREEN_EX}Devolped By zGhosty")
    print("")
    print(f"{Fore.LIGHTRED_EX}1- {Fore.LIGHTBLUE_EX}Escaneo Normal")
    print(f"{Fore.LIGHTRED_EX}2- {Fore.LIGHTBLUE_EX}Escaneo Bucle")
    print("")
    x=input(f"{Fore.LIGHTRED_EX}Selecciona una opcion: {Fore.LIGHTCYAN_EX}")
    if x=="1":
        os.system("clear")
        port=input(f"{Fore.LIGHTRED_EX}Ports: {Fore.LIGHTCYAN_EX}")
        ranges=input(f"{Fore.LIGHTRED_EX}Range: {Fore.LIGHTCYAN_EX}")
        print("\n")
        print(f"{Fore.LIGHTGREEN_EX}Configurando todo...")
        os.system("sudo java -Dfile.encoding=UTF-8 -jar quboscanner-0.3.6-jar-with-dependencies.jar -th 8000 -ti 500 -noping -nooutput -ports "+port+" -range "+ranges)
        print("")
        input(f"{Fore.LIGHTRED_EX}Escaneo Terminado, Pulsa Enter Para Volver al menu")
    elif x=="2":
        os.system("clear")
        print("Cuantos Bucles Quieres?")
        print("")
        print(f"{Fore.LIGHTRED_EX}1 - {Fore.LIGHTBLUE_EX}1 bucles")
        print(f"{Fore.LIGHTRED_EX}2 - {Fore.LIGHTBLUE_EX}2 bucles")
        print(f"{Fore.LIGHTRED_EX}3 - {Fore.LIGHTBLUE_EX}3 bucles")
        print(f"{Fore.LIGHTRED_EX}4 - {Fore.LIGHTBLUE_EX}4 bucles")
        print(f"{Fore.LIGHTRED_EX}5 - {Fore.LIGHTBLUE_EX}5 bucles")
        print("")
        bucles=input(f"{Fore.LIGHTBLUE_EX}Selecciona cuantos bucles quieres: {Fore.LIGHTCYAN_EX}")
        print("")
        print(f"{Fore.LIGHTGREEN_EX}CONFIGURANDO LOS BUCLES...")
        time.sleep(3)
        print("")
        print(f"{Fore.LIGHTGREEN_EX}Listo Pusiste {bucles} Bucles!{Fore.LIGHTCYAN_EX}")
        print("")
        if bucles=="1":
            ip1=input(f"{Fore.LIGHTRED_EX}Range 1: {Fore.LIGHTCYAN_EX}")
            os.system("sudo java -Dfile.encoding=UTF-8 -jar quboscanner-0.3.6-jar-with-dependencies.jar -th 8000 -ti 500 -noping -nooutput -ports 25566-25599 -range "+ip1)
            print("")
            input(f"{Fore.LIGHTRED_EX}Escaneo Terminado, Pulsa Enter Para Volver al menu")
        elif bucles=="2":
            ip2=input(f"{Fore.LIGHTRED_EX}Range 1: {Fore.LIGHTCYAN_EX}")
            ip3=input(f"{Fore.LIGHTRED_EX}Range 2: {Fore.LIGHTCYAN_EX}")
            print("\n")
            os.system("sudo java -Dfile.encoding=UTF-8 -jar quboscanner-0.3.6-jar-with-dependencies.jar -th 8000 -ti 500 -noping -nooutput -ports 25566-25599 -range "+ip2)
            print("\n")
            os.system("sudo java -Dfile.encoding=UTF-8 -jar quboscanner-0.3.6-jar-with-dependencies.jar -th 8000 -ti 500 -noping -nooutput -ports 25566-25599 -range "+ip3)
            print("")
            input(f"{Fore.LIGHTRED_EX}Escaneo Terminado, Pulsa Enter Para Volver al menu")
        elif bucles=="3":
            ip4=input(f"{Fore.LIGHTRED_EX}Range 1: {Fore.LIGHTCYAN_EX}")
            ip5=input(f"{Fore.LIGHTRED_EX}Range 2: {Fore.LIGHTCYAN_EX}")
            ip6=input(f"{Fore.LIGHTRED_EX}Range 3: {Fore.LIGHTCYAN_EX}")
            print("\n")
            os.system("sudo java -Dfile.encoding=UTF-8 -jar quboscanner-0.3.6-jar-with-dependencies.jar -th 8000 -ti 500 -noping -nooutput -ports 25566-25599 -range "+ip4)
            print("\n")
            os.system("sudo java -Dfile.encoding=UTF-8 -jar quboscanner-0.3.6-jar-with-dependencies.jar -th 8000 -ti 500 -noping -nooutput -ports 25566-25599 -range "+ip5)
            print("\n")
            os.system("sudo java -Dfile.encoding=UTF-8 -jar quboscanner-0.3.6-jar-with-dependencies.jar -th 8000 -ti 500 -noping -nooutput -ports 25566-25599 -range "+ip6)
            print("")
            input(f"{Fore.LIGHTRED_EX}Escaneo Terminado, Pulsa Enter Para Volver al menu")
        elif bucles=="4":
            ip7=input(f"{Fore.LIGHTRED_EX}Range 1: {Fore.LIGHTCYAN_EX}")
            ip8=input(f"{Fore.LIGHTRED_EX}Range 2: {Fore.LIGHTCYAN_EX}")
            ip9=input(f"{Fore.LIGHTRED_EX}Range 3: {Fore.LIGHTCYAN_EX}")
            ip10=input(f"{Fore.LIGHTRED_EX}Range 4: {Fore.LIGHTCYAN_EX}")
            print("\n")
            os.system("sudo java -Dfile.encoding=UTF-8 -jar quboscanner-0.3.6-jar-with-dependencies.jar -th 8000 -ti 500 -noping -nooutput -ports 25566-25599 -range "+ip7)
            print("\n")
            os.system("sudo java -Dfile.encoding=UTF-8 -jar quboscanner-0.3.6-jar-with-dependencies.jar -th 8000 -ti 500 -noping -nooutput -ports 25566-25599 -range "+ip8)
            print("\n")
            os.system("sudo java -Dfile.encoding=UTF-8 -jar quboscanner-0.3.6-jar-with-dependencies.jar -th 8000 -ti 500 -noping -nooutput -ports 25566-25599 -range "+ip9)
            print("\n")
            os.system("sudo java -Dfile.encoding=UTF-8 -jar quboscanner-0.3.6-jar-with-dependencies.jar -th 8000 -ti 500 -noping -nooutput -ports 25566-25599 -range "+ip10)
            print("")
            input(f"{Fore.LIGHTRED_EX}Escaneo Terminado, Pulsa Enter Para Volver al menu")
        elif bucles=="5":
            ip11=input(f"{Fore.LIGHTRED_EX}Range 1: {Fore.LIGHTCYAN_EX}")
            ip12=input(f"{Fore.LIGHTRED_EX}Range 2: {Fore.LIGHTCYAN_EX}")
            ip13=input(f"{Fore.LIGHTRED_EX}Range 3: {Fore.LIGHTCYAN_EX}")
            ip14=input(f"{Fore.LIGHTRED_EX}Range 4: {Fore.LIGHTCYAN_EX}")
            ip15=input(f"{Fore.LIGHTRED_EX}Range 5: {Fore.LIGHTCYAN_EX}")
            print("\n")
            os.system("sudo java -Dfile.encoding=UTF-8 -jar quboscanner-0.3.6-jar-with-dependencies.jar -th 8000 -ti 500 -noping -nooutput -ports 25566-25599 -range "+ip11)
            print("\n")
            os.system("sudo java -Dfile.encoding=UTF-8 -jar quboscanner-0.3.6-jar-with-dependencies.jar -th 8000 -ti 500 -noping -nooutput -ports 25566-25599 -range "+ip12)
            print("\n")
            os.system("sudo java -Dfile.encoding=UTF-8 -jar quboscanner-0.3.6-jar-with-dependencies.jar -th 8000 -ti 500 -noping -nooutput -ports 25566-25599 -range "+ip13)
            print("\n")
            os.system("sudo java -Dfile.encoding=UTF-8 -jar quboscanner-0.3.6-jar-with-dependencies.jar -th 8000 -ti 500 -noping -nooutput -ports 25566-25599 -range "+ip14)
            print("\n")
            os.system("sudo java -Dfile.encoding=UTF-8 -jar quboscanner-0.3.6-jar-with-dependencies.jar -th 8000 -ti 500 -noping -nooutput -ports 25566-25599 -range "+ip15)
            print("")
            input(f"{Fore.LIGHTRED_EX}Escaneo Terminado, Pulsa Enter Para Volver al menu")

        else:
            input(f"{Fore.LIGHTCYAN_EX}Selecciona una opcion :/")

    else:
        input(f"{Fore.LIGHTCYAN_EX}Selecciona una opcion :/")